apiVersion: apps/v1
kind: Deployment
metadata:
  name: rabitmqexam
spec:
  selector:
    matchLabels:
      app: rabitmqexam
  template:
    metadata:
      labels:
        app: rabitmqexam
    spec:
      containers:
      - name: rabitmqexam
        image: rabbitmq:3.9-management

---
apiVersion: v1
kind: Service
metadata:
  name: rabitmqexam
spec:
  type: NodePort
  selector:
    app: rabitmqexam
  ports:
  - port: 80
    targetPort: 15672
    nodePort: 32000
    name: "management"